-- MySQL Script generated by MySQL Workbench
-- seg 29 ago 2022 11:49:45
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cliente` (
  `idcliente` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  `cpf` VARCHAR(14) NULL,
  `contato` VARCHAR(45) NULL,
  PRIMARY KEY (`idcliente`))
ENGINE = MEMORY;


-- -----------------------------------------------------
-- Table `mydb`.`pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pedido` (
  `idpedido` INT NOT NULL,
  `serviço` VARCHAR(45) NULL,
  `descriçao` VARCHAR(45) NULL,
  `data_da_solicitaçao` DATE NULL,
  `liberado` TINYINT NULL,
  `cliente_idcliente` INT NOT NULL,
  PRIMARY KEY (`idpedido`, `cliente_idcliente`),
  INDEX `fk_pedido_cliente1_idx` (`cliente_idcliente` ASC) VISIBLE,
  CONSTRAINT `fk_pedido_cliente1`
    FOREIGN KEY (`cliente_idcliente`)
    REFERENCES `mydb`.`cliente` (`idcliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`responsavel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`responsavel` (
  `idresponsavel` INT NOT NULL,
  `nivel_help_desk` INT NULL,
  `nome` VARCHAR(45) NULL,
  `departamento` VARCHAR(45) NULL,
  PRIMARY KEY (`idresponsavel`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ordem de serviço`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ordem de serviço` (
  `idordem_de_serviço` INT NOT NULL,
  `status` VARCHAR(45) NULL,
  PRIMARY KEY (`idordem_de_serviço`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ordem_de_serviço`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ordem_de_serviço` (
  `idordem_de_serviço` INT NOT NULL,
  `status` VARCHAR(45) NULL,
  `pedido_idpedido` INT NOT NULL,
  PRIMARY KEY (`idordem_de_serviço`, `pedido_idpedido`),
  INDEX `fk_ordem_de_serviço_pedido1_idx` (`pedido_idpedido` ASC) VISIBLE,
  CONSTRAINT `fk_ordem_de_serviço_pedido1`
    FOREIGN KEY (`pedido_idpedido`)
    REFERENCES `mydb`.`pedido` (`idpedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`analise_de_pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`analise_de_pedido` (
  `pedido_idpedido` INT NOT NULL,
  `responsavel_idresponsavel` INT NOT NULL,
  PRIMARY KEY (`pedido_idpedido`, `responsavel_idresponsavel`),
  INDEX `fk_pedido_has_responsavel_responsavel1_idx` (`responsavel_idresponsavel` ASC) VISIBLE,
  INDEX `fk_pedido_has_responsavel_pedido1_idx` (`pedido_idpedido` ASC) VISIBLE,
  CONSTRAINT `fk_pedido_has_responsavel_pedido1`
    FOREIGN KEY (`pedido_idpedido`)
    REFERENCES `mydb`.`pedido` (`idpedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pedido_has_responsavel_responsavel1`
    FOREIGN KEY (`responsavel_idresponsavel`)
    REFERENCES `mydb`.`responsavel` (`idresponsavel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
